<?php

namespace Cybernerdie\LaravelTerminalAfrica\Traits;

trait RateTrait
{
 /**
     * Endpoint for rate API calls
     *
     * @var string
     */
    const RATE_ENDPOINT = 'rates/';

    /**
     * This endpoint allows you to get a list of all rates generated by a user.
     *
     * @return array
     */
    public function getRates()
    {
        $endpoint = self::RATE_ENDPOINT;
        $method = 'GET';

        return $this->makeRequest($endpoint, $method);
    }


    /**
     * This endpoint allows you to retrieve details of a specific shipping rate.
     *
     * @param string $rateId
     * @return array
     */
    public function getRate(string $rateId)
    {
        $endpoint = self::RATE_ENDPOINT . $rateId;
        $method = 'GET';

        return $this->makeRequest($endpoint, $method);
    }
}
