<?php

namespace Cybernerdie\LaravelTerminalAfrica\Traits;

trait RateApi
{
    /**
     * Endpoint for rate API calls
     *
     * @var string
     */
    const RATE_ENDPOINT = '/rates';

    /**
     * This endpoint allows you to get a list of all rates generated by a user.
     *
     * @return array
     */
    public function getRates(): array
    {
        $endpoint = sprintf('%s', self::RATE_ENDPOINT);

        return $this->makeRequest(
            method: 'GET',
            endpoint: $endpoint
        );
    }

    /**
     * This endpoint allows you to retrieve details of a specific shipping rate.
     *
     * @param string $rateId
     * @return array
     */
    public function getRate(string $rateId): array
    {
        $endpoint = sprintf('%s/%s', self::RATE_ENDPOINT, $rateId);

        return $this->makeRequest(
            method: 'GET',
            endpoint: $endpoint
        );
    }

    /**
     * This method allows you to retrieve rates for a shipment.
     *
     * @param array $formParams
     * @return array
     */
    public function getRateForShipment(array $formParams): array
    {
        $endpoint = sprintf('%s/shipment', self::RATE_ENDPOINT);

        return $this->makeRequest(
            method: 'GET',
            endpoint: $endpoint,
            formParams: $formParams
        );
    }

    /**
     * This method allows you to retrieve rates for a shipment.
     *
     * @param array $formParams
     * @return array
     */
    public function getRateForMultiParcelShipment(array $formParams): array
    {
        $endpoint = sprintf('%s/multi/shipment', self::RATE_ENDPOINT);

        return $this->makeRequest(
            method: 'GET',
            endpoint: $endpoint,
            formParams: $formParams
        );
    }
}
