<?php

namespace Cybernerdie\LaravelTerminalAfrica\Traits;

use Cybernerdie\LaravelTerminalAfrica\Constants\TerminalAfricaConstant;

trait RateApi
{
    /**
     * This endpoint allows you to get a list of all rates generated by a user.
     */
    public function getRates(array $queryParams = []): array
    {
        $endpoint = sprintf('%s', TerminalAfricaConstant::RATE_ENDPOINT);

        return $this->makeRequest(
            method: 'GET',
            endpoint: $endpoint,
            queryParams: $queryParams
        );
    }

    /**
     * This endpoint allows you to retrieve details of a specific shipping rate.
     */
    public function getRate(string $rateId): array
    {
        $endpoint = sprintf('%s/%s', TerminalAfricaConstant::RATE_ENDPOINT, $rateId);

        return $this->makeRequest(
            method: 'GET',
            endpoint: $endpoint
        );
    }

    /**
     * This method allows you to retrieve rates for a shipment.
     */
    public function getRateForShipment(array $formParams): array
    {
        $endpoint = sprintf('%s/shipment', TerminalAfricaConstant::RATE_ENDPOINT);

        return $this->makeRequest(
            method: 'GET',
            endpoint: $endpoint,
            formParams: $formParams
        );
    }

    /**
     * This method allows you to retrieve rates for a shipment.
     */
    public function getRateForMultiParcelShipment(array $formParams): array
    {
        $endpoint = sprintf('%s/multi/shipment', TerminalAfricaConstant::RATE_ENDPOINT);

        return $this->makeRequest(
            method: 'GET',
            endpoint: $endpoint,
            formParams: $formParams
        );
    }
}
